version : "3"
services:
  mongo:
    image : "mongo"
    volumes:
      - mongorepo:/data/db
    network_mode: host
  
  redis:
    image : "redis"
    network_mode: host
    volumes:
      - redisdata:/data

  binance:
    image : arnoldyoussa/trading_opa:latest
    volumes:
      - oparepo:/app/db
    ports:
      - 8050:8050
    depends_on:
      - mongo
      - redis
    network_mode: host

volumes:
  mongorepo:
  oparepo:
  redisdata:
